# Generated by Django 5.2.8 on 2025-12-26 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_certifications_file'),
        ('tours', '0003_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_point_latitude',
            field=models.DecimalField(decimal_places=6, default=1.1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_point_longitude',
            field=models.DecimalField(decimal_places=6, default=1.1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.tour'),
        ),
        migrations.CreateModel(
            name='CustomTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_point_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_point_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tours', to='guides.guideprofile')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tours', to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tours', to='guides.wilaya')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.customtour'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_tour__isnull', True), ('tour__isnull', False)), models.Q(('custom_tour__isnull', False), ('tour__isnull', True)), _connector='OR'), name='booking_tour_xor_custom_tour'),
        ),
    ]
