# Generated by Django 5.2.8 on 2025-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_created_at_tour_start_point_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtour',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
            preserve_default=False,
        ),
    ]
