# Generated by Django 5.2.8 on 2025-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_customtour_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
