# Generated by Django 5.2.8 on 2025-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_average_rating_tour_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpicture',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
