# Generated by Django 5.2.8 on 2025-12-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourpicture_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpicture',
            name='caption',
        ),
    ]
