# Generated by Django 5.2.8 on 2025-12-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_tourpicture_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpicture',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
