# Generated by Django 5.2.8 on 2025-12-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourpicture_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpicture',
            name='is_primary',
        ),
    ]
