# Generated by Django 5.2.8 on 2025-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tourpicture_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='start_point_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_point_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
    ]
