# Generated by Django 5.2.8 on 2025-12-30 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guideprofile_average_rating_and_more'),
        ('tours', '0011_alter_tour_start_point_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='start_point_latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_point_longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='guides.wilaya'),
        ),
    ]
