# Generated by Django 5.2.8 on 2025-11-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
