# Generated by Django 5.2.8 on 2025-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_certifications_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
